doctor_local = [
{ 'DoctorID': 46,
    'DoctorName': 'عمرو الجبري',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 3, 'Levels': [{'LevelID': 2, 'CoursesID': [103]}]}],
    'availability_Appointments': [ { 'Appointments': 42,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [1, 1, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
    { 'DoctorID': 40,
    'DoctorName': 'اسماعيل',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 3, 'Levels': [{'LevelID': 2, 'CoursesID': [97]}]}],
    'availability_Appointments': [ { 'Appointments': 34,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [1, 1, 0, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 41,
    'DoctorName': 'مهند',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 3, 'Levels': [{'LevelID': 2, 'CoursesID': [98]}]}],
    'availability_Appointments': [ { 'Appointments': 37,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [1, 1, 1, 1],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [1, 1, 1, 1]}}]},
  { 'DoctorID': 42,
    'DoctorName': 'شمسان للشريف',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 3, 'Levels': [{'LevelID': 2, 'CoursesID': [99, 100]}]}],
    'availability_Appointments': [ { 'Appointments': 38,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [1, 1, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 43,
    'DoctorName': 'ماهر',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 3, 'Levels': [{'LevelID': 2, 'CoursesID': [101]}]}],
    'availability_Appointments': [ { 'Appointments': 39,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [0, 0, 1, 1],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 44,
    'DoctorName': 'ناظم',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 3, 'Levels': [{'LevelID': 2, 'CoursesID': [102]}]}],
    'availability_Appointments': [ { 'Appointments': 40,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [1, 1, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 50,
    'DoctorName': 'مستشار',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 3, 'Levels': [{'LevelID': 1, 'CoursesID': [74]}]}],
    'availability_Appointments': [ { 'Appointments': 47,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [1, 0, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
    { 'DoctorID': 14,
    'DoctorName': 'عادل',
    'HasMultipleAppointments': 0,
    'CourseTaught': [ {'DepartmentID': 1, 'Levels': [{'LevelID': 1, 'CoursesID': [65]}]},
                      {'DepartmentID': 3, 'Levels': [{'LevelID': 1, 'CoursesID': [65]}]}],
    'availability_Appointments': [ { 'Appointments': 48,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [0, 1, 1, 0],
                                                       'Tuesday': [0, 1, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 15,
    'DoctorName': 'الوشلي',
    'HasMultipleAppointments': 0,
    'CourseTaught': [ {'DepartmentID': 1, 'Levels': [{'LevelID': 1, 'CoursesID': [67]}]},
                      {'DepartmentID': 3, 'Levels': [{'LevelID': 1, 'CoursesID': [67]}]}],
    'availability_Appointments': [ { 'Appointments': 36,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [0, 1, 0, 0],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [0, 0, 1, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 16,
    'DoctorName': 'شكري',
    'HasMultipleAppointments': 0,
    'CourseTaught': [ { 'DepartmentID': 1,
                        'Levels': [ {'LevelID': 1, 'CoursesID': [69]},
                                    {'LevelID': 2, 'CoursesID': [82]},
                                    {'LevelID': 3, 'CoursesID': [86]}]}],
    'availability_Appointments': [ { 'Appointments': 9,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [0, 1, 1, 0],
                                                       'Wednesday': [1, 1, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 17,
    'DoctorName': 'مختار المنصوب',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 1, 'Levels': [{'LevelID': 1, 'CoursesID': [72]}]}],
    'availability_Appointments': [ { 'Appointments': 10,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [1, 1, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 18,
    'DoctorName': 'عبد الحميد الطيب',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 1, 'Levels': [{'LevelID': 1, 'CoursesID': [75]}]}],
    'availability_Appointments': [ { 'Appointments': 11,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [1, 0, 0, 0]}}]},
  { 'DoctorID': 19,
    'DoctorName': 'صلاح المجاهد',
    'HasMultipleAppointments': 0,
    'CourseTaught': [ { 'DepartmentID': 1,
                        'Levels': [{'LevelID': 2, 'CoursesID': [77]}, {'LevelID': 3, 'CoursesID': [68]}]}],
    'availability_Appointments': [ { 'Appointments': 12,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [1, 1, 0, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 20,
    'DoctorName': 'يوسف',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 1, 'Levels': [{'LevelID': 2, 'CoursesID': [81]}]}],
    'availability_Appointments': [ { 'Appointments': 13,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 1, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 21,
    'DoctorName': 'اسرار',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 1, 'Levels': [{'LevelID': 2, 'CoursesID': [51]}]}],
    'availability_Appointments': [ { 'Appointments': 14,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [1, 1, 1, 1],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 22,
    'DoctorName': 'مجيب',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 1, 'Levels': [{'LevelID': 2, 'CoursesID': [52]}]}],
    'availability_Appointments': [ { 'Appointments': 15,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [1, 1, 1, 1],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 23,
    'DoctorName': 'ارتفاع',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 1, 'Levels': [{'LevelID': 2, 'CoursesID': [53]}]}],
    'availability_Appointments': [ { 'Appointments': 16,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [1, 1, 1, 1],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 24,
    'DoctorName': 'الاحمدي',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 1, 'Levels': [{'LevelID': 2, 'CoursesID': [54]}]}],
    'availability_Appointments': [ { 'Appointments': 17,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [1, 1, 1, 1],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 25,
    'DoctorName': 'عارف',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 1, 'Levels': [{'LevelID': 2, 'CoursesID': [83]}]}],
    'availability_Appointments': [ { 'Appointments': 18,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [1, 0, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 26,
    'DoctorName': 'هاشم',
    'HasMultipleAppointments': 0,
    'CourseTaught': [ { 'DepartmentID': 1,
                        'Levels': [{'LevelID': 2, 'CoursesID': [56]}, {'LevelID': 3, 'CoursesID': [62]}]}],
    'availability_Appointments': [ { 'Appointments': 19,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [0, 1, 1, 0],
                                                       'Tuesday': [0, 0, 1, 1],
                                                       'Wednesday': [0, 0, 1, 1],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 27,
    'DoctorName': 'خلود',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 1, 'Levels': [{'LevelID': 2, 'CoursesID': [55]}]}],
    'availability_Appointments': [ { 'Appointments': 20,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [0, 1, 1, 0],
                                                       'Tuesday': [0, 0, 1, 1],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 28,
    'DoctorName': 'انس',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 1, 'Levels': [{'LevelID': 2, 'CoursesID': [84]}]}],
    'availability_Appointments': [ { 'Appointments': 21,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [1, 0, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 29,
    'DoctorName': 'وداد',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 1, 'Levels': [{'LevelID': 3, 'CoursesID': [70]}]}],
    'availability_Appointments': [ { 'Appointments': 22,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 1, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 31,
    'DoctorName': 'اسوان',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 1, 'Levels': [{'LevelID': 3, 'CoursesID': [76]}]}],
    'availability_Appointments': [ { 'Appointments': 24,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [0, 1, 0, 0],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 32,
    'DoctorName': 'صهيب',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 1, 'Levels': [{'LevelID': 3, 'CoursesID': [57]}]}],
    'availability_Appointments': [ { 'Appointments': 25,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [1, 1, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 33,
    'DoctorName': 'سميرة',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 1, 'Levels': [{'LevelID': 3, 'CoursesID': [58]}]}],
    'availability_Appointments': [ { 'Appointments': 26,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [1, 1, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 37,
    'DoctorName': 'ماجد السياني',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 2, 'Levels': [{'LevelID': 4, 'CoursesID': [90]}]}],
    'availability_Appointments': [ { 'Appointments': 30,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [1, 0, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 38,
    'DoctorName': 'منير',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 2, 'Levels': [{'LevelID': 4, 'CoursesID': [87]}]}],
    'availability_Appointments': [ { 'Appointments': 31,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [1, 0, 0, 0],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
   { 'DoctorID': 34,
    'DoctorName': 'عبدربه',
    'HasMultipleAppointments': 0,
    'CourseTaught': [ { 'DepartmentID': 1,
                        'Levels': [{'LevelID': 3, 'CoursesID': [59]}, {'LevelID': 4, 'CoursesID': [63]}]},
                      {'DepartmentID': 2, 'Levels': [{'LevelID': 4, 'CoursesID': [88]}]}],

    'availability_Appointments': [ { 'Appointments': 43,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [1, 1, 0, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [0, 1, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [1, 1, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 35,
    'DoctorName': 'احمد فؤاد',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 1, 'Levels': [{'LevelID': 3, 'CoursesID': [60]}]}],
    'availability_Appointments': [ { 'Appointments': 28,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [0, 0, 1, 1],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 36,
    'DoctorName': 'حمدي',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 1, 'Levels': [{'LevelID': 3, 'CoursesID': [61]}]}],
    'availability_Appointments': [ { 'Appointments': 29,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [1, 1, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},


  { 'DoctorID': 51,
    'DoctorName': 'منصور القباطي',
    'HasMultipleAppointments': 0,
    'CourseTaught': [ { 'DepartmentID': 1,
                        'Levels': [{'LevelID': 3, 'CoursesID': [73]}, {'LevelID': 4, 'CoursesID': [80]}]},
                      {'DepartmentID': 2, 'Levels': [{'LevelID': 4, 'CoursesID': [80]}]}],
    'availability_Appointments': [ { 'Appointments': 52,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [0, 1, 1, 0],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [0, 1, 0, 0]}}]},

  { 'DoctorID': 39,
    'DoctorName': 'فلاح مبارك',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 3, 'Levels': [{'LevelID': 1, 'CoursesID': [95]}]}],
    'availability_Appointments': [ { 'Appointments': 49,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [1, 1, 0, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
    { 'DoctorID': 45,
    'DoctorName': 'عبدالله العبادي',
    'HasMultipleAppointments': 0,
    'CourseTaught': [ { 'DepartmentID': 3,
                        'Levels': [{'LevelID': 1, 'CoursesID': [92]}, {'LevelID': 2, 'CoursesID': [104]}]}],
    'availability_Appointments': [ { 'Appointments': 51,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [0, 0, 1, 0],
                                                       'Wednesday': [0, 1, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 47,
    'DoctorName': 'طلال',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 3, 'Levels': [{'LevelID': 1, 'CoursesID': [75]}]}],
    'availability_Appointments': [ { 'Appointments': 50,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [1, 0, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 48,
    'DoctorName': 'لينا عبدالله',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 3, 'Levels': [{'LevelID': 1, 'CoursesID': [96]}]}],
    'availability_Appointments': [ { 'Appointments': 45,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [1, 0, 0, 0],
                                                       'Monday': [0, 0, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [0, 0, 0, 0]}}]},
  { 'DoctorID': 49,
    'DoctorName': 'أصيل',
    'HasMultipleAppointments': 0,
    'CourseTaught': [{'DepartmentID': 3, 'Levels': [{'LevelID': 1, 'CoursesID': [91]}]}],
    'availability_Appointments': [ { 'Appointments': 46,
                                     'Attendance': 'لا يوجد تفضيل',
                                     'availability': { 'Saturday': [0, 0, 0, 0],
                                                       'Sunday': [0, 0, 0, 0],
                                                       'Monday': [1, 1, 0, 0],
                                                       'Tuesday': [0, 0, 0, 0],
                                                       'Wednesday': [0, 0, 0, 0],
                                                       'Thursday': [1, 1, 0, 0]}}]},]


# --- Data for: Departments ---
Departments = [
    { 'DepartmentID': 1,
    'DepartmentName': 'تقنية معلومات',
    'HasLevel5': 0,
    'HasLevel6': 0,
    'Levels': [ { 'LevelID': 1,
                  'LevelName': 'المستوى الأول',
                  'StudentCount': 93,
                  'LectureDayCount': 2,
                  'Courses': { 'Theoretical': [ {'CourseID': 64, 'GroupsCount': 2, 'LinkedPracticalID': 85},
                                                {'CourseID': 65, 'GroupsCount': 2, 'LinkedPracticalID': None},
                                                {'CourseID': 67, 'GroupsCount': 1, 'LinkedPracticalID': None},
                                                {'CourseID': 69, 'GroupsCount': 2, 'LinkedPracticalID': None},
                                                {'CourseID': 72, 'GroupsCount': 2, 'LinkedPracticalID': None},
                                                {'CourseID': 74, 'GroupsCount': 1, 'LinkedPracticalID': None},
                                                {'CourseID': 75, 'GroupsCount': 1, 'LinkedPracticalID': None}],
                               'Practical': [ { 'CourseID': 85,
                                                'GroupsCount': 4,
                                                'AssistantsCount': 0,
                                                'RoomIsPrimary': 0,
                                                'Rooms': [{'RoomID': 10, 'Priority': 1}]}]}},
                { 'LevelID': 2,
                  'LevelName': 'المستوى الثاني',
                  'StudentCount': 82,
                  'LectureDayCount': 3,
                  'Courses': { 'Theoretical': [ {'CourseID': 77, 'GroupsCount': 1, 'LinkedPracticalID': 51},
                                                {'CourseID': 79, 'GroupsCount': 1, 'LinkedPracticalID': 52},
                                                {'CourseID': 81, 'GroupsCount': 1, 'LinkedPracticalID': 56},
                                                {'CourseID': 82, 'GroupsCount': 1, 'LinkedPracticalID': 54},
                                                {'CourseID': 83, 'GroupsCount': 1, 'LinkedPracticalID': 55},
                                                {'CourseID': 84, 'GroupsCount': 1, 'LinkedPracticalID': 53}],
                               'Practical': [ { 'CourseID': 51,
                                                'GroupsCount': 4,
                                                'AssistantsCount': 0,
                                                'RoomIsPrimary': 1,
                                                'Rooms': [{'RoomID': 11, 'Priority': 1}]},
                                              { 'CourseID': 52,
                                                'GroupsCount': 4,
                                                'AssistantsCount': 0,
                                                'RoomIsPrimary': 1,
                                                'Rooms': [{'RoomID': 10, 'Priority': 1}]},
                                              { 'CourseID': 53,
                                                'GroupsCount': 4,
                                                'AssistantsCount': 0,
                                                'RoomIsPrimary': 1,
                                                'Rooms': [{'RoomID': 13, 'Priority': 1}]},
                                              { 'CourseID': 54,
                                                'GroupsCount': 4,
                                                'AssistantsCount': 0,
                                                'RoomIsPrimary': 1,
                                                'Rooms': [{'RoomID': 12, 'Priority': 1}]},
                                              { 'CourseID': 55,
                                                'GroupsCount': 4,
                                                'AssistantsCount': 0,
                                                'RoomIsPrimary': 1,
                                                'Rooms': [{'RoomID': 11, 'Priority': 1}]},
                                              { 'CourseID': 56,
                                                'GroupsCount': 4,
                                                'AssistantsCount': 0,
                                                'RoomIsPrimary': 1,
                                                'Rooms': [{'RoomID': 13, 'Priority': 1}]}]}},
                { 'LevelID': 3,
                  'LevelName': 'المستوى الثالث',
                  'StudentCount': 60,
                  'LectureDayCount': 3,
                  'Courses': { 'Theoretical': [ {'CourseID': 66, 'GroupsCount': 1, 'LinkedPracticalID': 57},
                                                {'CourseID': 68, 'GroupsCount': 1, 'LinkedPracticalID': 59},
                                                {'CourseID': 70, 'GroupsCount': 1, 'LinkedPracticalID': None},
                                                {'CourseID': 71, 'GroupsCount': 1, 'LinkedPracticalID': 61},
                                                {'CourseID': 73, 'GroupsCount': 1, 'LinkedPracticalID': 58},
                                                {'CourseID': 76, 'GroupsCount': 1, 'LinkedPracticalID': 62},
                                                {'CourseID': 86, 'GroupsCount': 1, 'LinkedPracticalID': 60}],
                               'Practical': [ { 'CourseID': 57,
                                                'GroupsCount': 2,
                                                'AssistantsCount': 0,
                                                'RoomIsPrimary': 1,
                                                'Rooms': [{'RoomID': 12, 'Priority': 1}]},
                                              { 'CourseID': 58,
                                                'GroupsCount': 2,
                                                'AssistantsCount': 0,
                                                'RoomIsPrimary': 1,
                                                'Rooms': [{'RoomID': 11, 'Priority': 1}]},
                                              { 'CourseID': 59,
                                                'GroupsCount': 2,
                                                'AssistantsCount': 0,
                                                'RoomIsPrimary': 1,
                                                'Rooms': [{'RoomID': 12, 'Priority': 1}]},
                                              { 'CourseID': 60,
                                                'GroupsCount': 2,
                                                'AssistantsCount': 0,
                                                'RoomIsPrimary': 1,
                                                'Rooms': [{'RoomID': 10, 'Priority': 1}]},
                                              { 'CourseID': 61,
                                                'GroupsCount': 2,
                                                'AssistantsCount': 0,
                                                'RoomIsPrimary': 1,
                                                'Rooms': [{'RoomID': 11, 'Priority': 1}]},
                                              { 'CourseID': 62,
                                                'GroupsCount': 2,
                                                'AssistantsCount': 0,
                                                'RoomIsPrimary': 1,
                                                'Rooms': [{'RoomID': 11, 'Priority': 1}]}]}},
                { 'LevelID': 4,
                  'LevelName': 'المستوى الرابع',
                  'StudentCount': 43,
                  'LectureDayCount': 2,
                  'Courses': { 'Theoretical': [ {'CourseID': 78, 'GroupsCount': 1, 'LinkedPracticalID': 63},
                                                {'CourseID': 80, 'GroupsCount': 1, 'LinkedPracticalID': None}],
                               'Practical': [ { 'CourseID': 63,
                                                'GroupsCount': 2,
                                                'AssistantsCount': 0,
                                                'RoomIsPrimary': 1,
                                                'Rooms': [{'RoomID': 13, 'Priority': 1}]}]}}]},
  { 'DepartmentID': 3,
    'DepartmentName': 'هندسة معمارية',
    'HasLevel5': 0,
    'HasLevel6': 0,
    'Levels': [ { 'LevelID': 1,
                  'LevelName': 'المستوى الأول',
                  'StudentCount': 35,
                  'LectureDayCount': 3,
                  'Courses': { 'Theoretical': [ {'CourseID': 65, 'GroupsCount': 1, 'LinkedPracticalID': None},
                                                {'CourseID': 67, 'GroupsCount': 1, 'LinkedPracticalID': None},
                                                {'CourseID': 74, 'GroupsCount': 1, 'LinkedPracticalID': None},
                                                {'CourseID': 75, 'GroupsCount': 1, 'LinkedPracticalID': None},
                                                {'CourseID': 92, 'GroupsCount': 1, 'LinkedPracticalID': None},
                                                {'CourseID': 96, 'GroupsCount': 1, 'LinkedPracticalID': None}],
                               'Practical': [ { 'CourseID': 91,
                                                'GroupsCount': 2,
                                                'AssistantsCount': 0,
                                                'RoomIsPrimary': 1,
                                                'Rooms': [{'RoomID': 14, 'Priority': 1}]},
                                              { 'CourseID': 95,
                                                'GroupsCount': 1,
                                                'AssistantsCount': 0,
                                                'RoomIsPrimary': 1,
                                                'Rooms': [{'RoomID': 14, 'Priority': 1}]}]}},
                { 'LevelID': 2,
                  'LevelName': 'المستوى الثاني',
                  'StudentCount': 27,
                  'LectureDayCount': 3,
                  'Courses': { 'Theoretical': [ {'CourseID': 97, 'GroupsCount': 1, 'LinkedPracticalID': None},
                                                {'CourseID': 99, 'GroupsCount': 1, 'LinkedPracticalID': None},
                                                {'CourseID': 100, 'GroupsCount': 1, 'LinkedPracticalID': None}],
                               'Practical': [ { 'CourseID': 98,
                                                'GroupsCount': 1,
                                                'AssistantsCount': 0,
                                                'RoomIsPrimary': 1,
                                                'Rooms': [{'RoomID': 15, 'Priority': 1}]},
                                              { 'CourseID': 101,
                                                'GroupsCount': 1,
                                                'AssistantsCount': 0,
                                                'RoomIsPrimary': 1,
                                                'Rooms': [{'RoomID': 15, 'Priority': 1}]},
                                              { 'CourseID': 102,
                                                'GroupsCount': 1,
                                                'AssistantsCount': 0,
                                                'RoomIsPrimary': 1,
                                                'Rooms': [{'RoomID': 13, 'Priority': 1}]},
                                              { 'CourseID': 103,
                                                'GroupsCount': 1,
                                                'AssistantsCount': 0,
                                                'RoomIsPrimary': 0,
                                                'Rooms': [{'RoomID': 15, 'Priority': 1}]},
                                              { 'CourseID': 104,
                                                'GroupsCount': 1,
                                                'AssistantsCount': 0,
                                                'RoomIsPrimary': 1,
                                                'Rooms': [{'RoomID': 15, 'Priority': 1}]}]}}]},
    { 'DepartmentID': 2,
    'DepartmentName': 'نظم معلومات',
    'HasLevel5': 0,
    'HasLevel6': 0,
    'Levels': [ { 'LevelID': 4,
                  'LevelName': 'المستوى الرابع',
                  'StudentCount': 24,
                  'LectureDayCount': 2,
                  'Courses': { 'Theoretical': [ {'CourseID': 80, 'GroupsCount': 1, 'LinkedPracticalID': 88},
                                                {'CourseID': 87, 'GroupsCount': 1, 'LinkedPracticalID': None},
                                                {'CourseID': 89, 'GroupsCount': 1, 'LinkedPracticalID': None},
                                                {'CourseID': 90, 'GroupsCount': 1, 'LinkedPracticalID': None}],
                               'Practical': [ { 'CourseID': 88,
                                                'GroupsCount': 1,
                                                'AssistantsCount': 0,
                                                'RoomIsPrimary': 1,
                                                'Rooms': [{'RoomID': 12, 'Priority': 1}]}]}}]}]


# --- Data for: doctor_Employ ---
doctor_Employ = [
    { 'DoctorID': 11,
    'DoctorName': 'سحر المقطري',
    'CourseTaught': [{'DepartmentID': 1, 'Levels': [{'LevelID': 1, 'CoursesID': [85]}]}],
    'availability': { 'Saturday': [1, 1, 0, 0],
                      'Sunday': [0, 0, 0, 0],
                      'Monday': [0, 0, 0, 0],
                      'Tuesday': [1, 1, 0, 0],
                      'Wednesday': [0, 0, 0, 0],
                      'Thursday': [0, 0, 0, 0]}},
  { 'DoctorID': 12,
    'DoctorName': 'اماني علي',
    'CourseTaught': [ { 'DepartmentID': 1,
                        'Levels': [ {'LevelID': 1, 'CoursesID': [64]},
                                    {'LevelID': 2, 'CoursesID': [79]},
                                    {'LevelID': 3, 'CoursesID': [66, 71]},
                                    {'LevelID': 4, 'CoursesID': [78]}]},
                              {'DepartmentID': 2, 'Levels': [{'LevelID': 4, 'CoursesID': [89]}]}],

    'availability': { 'Saturday': [1, 1, 0, 0],
                      'Sunday': [1, 0, 1, 0], # <-- Note: Original had [1, 0, 1, 0], using yours [0, 0, 1, 0]
                      'Monday': [1, 1, 0, 0],
                      'Tuesday': [0, 0, 0, 0],
                      'Wednesday': [0, 0, 0, 0],
                      'Thursday': [1, 0, 0, 0]}},
  { 'DoctorID': 13,
    'DoctorName': 'صباح',
    'CourseTaught': [{'DepartmentID': 1, 'Levels': [{'LevelID': 1, 'CoursesID': [74]}]}],
    'availability': { 'Saturday': [0, 0, 0, 0],
                      'Sunday': [0, 0, 0, 0],
                      'Monday': [0, 0, 0, 0],
                      'Tuesday': [0, 0, 0, 0],
                      'Wednesday': [0, 0, 0, 0],
                      'Thursday': [0, 1, 0, 0]}}]


# --- Data for: Rooms ---
Rooms = [
    { 'RoomID': 4,
    'RoomName': '404',
    'Capacity': 48,
    'Type': 1,
    'Availability': { 'Saturday': [0, 0, 0, 0],
                      'Sunday': [0, 0, 0, 0],
                      'Monday': [1, 1, 0, 0],
                      'Tuesday': [0, 0, 0, 0],
                      'Wednesday': [0, 0, 0, 0],
                      'Thursday': [0, 0, 0, 0]}},
  { 'RoomID': 5,
    'RoomName': '410',
    'Capacity': 94,
    'Type': 1,
    'Availability': { 'Saturday': [1, 1, 1, 0],
                      'Sunday': [0, 0, 0, 0],
                      'Monday': [1, 1, 1, 0],
                      'Tuesday': [0, 0, 0, 0],
                      'Wednesday': [1, 1, 1, 0],
                      'Thursday': [0, 1, 0, 0]}},
  { 'RoomID': 6,
    'RoomName': '502',
    'Capacity': 48,
    'Type': 1,
    'Availability': { 'Saturday': [0, 0, 0, 0],
                      'Sunday': [1, 1, 1, 0],
                      'Monday': [1, 0, 0, 0],
                      'Tuesday': [0, 0, 0, 0],
                      'Wednesday': [0, 0, 0, 0],
                      'Thursday': [0, 1, 0, 0]}},
  { 'RoomID': 7,
    'RoomName': '505',
    'Capacity': 62,
    'Type': 1,
    'Availability': { 'Saturday': [1, 1, 1, 0],
                      'Sunday': [1, 1, 1, 0],
                      'Monday': [0, 0, 0, 0],
                      'Tuesday': [0, 0, 1, 0],
                      'Wednesday': [1, 1, 0, 0],
                      'Thursday': [1, 0, 0, 0]}}, # <-- Note: Original had [0,0,0,0], using yours [1,0,0,0]

  { 'RoomID': 9,
    'RoomName': '510',
    'Capacity': 94,
    'Type': 1,
    'Availability': { 'Saturday': [0, 0, 0, 0],
                      'Sunday': [0, 0, 0, 0],
                      'Monday': [0, 0, 0, 0],
                      'Tuesday': [1, 1, 0, 0],
                      'Wednesday': [0, 0, 0, 0],
                      'Thursday': [1, 0, 0, 0]}},
  { 'RoomID': 8,
    'RoomName': '507',
    'Capacity': 50,
    'Type': 1,
    'Availability': { 'Saturday': [1, 1, 0, 0],
                      'Sunday': [1, 1, 0, 0],
                      'Monday': [1, 1, 0, 0],
                      'Tuesday': [1, 1, 0, 0],
                      'Wednesday': [1, 1, 0, 0],
                      'Thursday': [1, 0, 0, 0]}},
  { 'RoomID': 10,
    'RoomName': 'معمل 1',
    'Capacity': 25,
    'Type': 0,
    'Availability': { 'Saturday': [1, 1, 0, 0],
                      'Sunday': [1, 1, 1, 1],
                      'Monday': [0, 0, 0, 0],
                      'Tuesday': [1, 1, 0, 0],
                      'Wednesday': [0, 0, 1, 1],
                      'Thursday': [0, 0, 0, 0]}},
  { 'RoomID': 11,
    'RoomName': 'معمل 2',
    'Capacity': 25,
    'Type': 0,
    'Availability': { 'Saturday': [0, 0, 0, 0],
                      'Sunday': [1, 1, 1, 1],
                      'Monday': [0, 1, 1, 0],
                      'Tuesday': [1, 1, 1, 1],
                      'Wednesday': [1, 1, 1, 1],
                      'Thursday': [0, 0, 0, 0]}},
  { 'RoomID': 12,
    'RoomName': 'معمل 3',
    'Capacity': 25,
    'Type': 0,
    'Availability': { 'Saturday': [0, 0, 0, 0],
                      'Sunday': [1, 1, 1, 1],
                      'Monday': [0, 1, 0, 0],
                      'Tuesday': [1, 1, 0, 0],
                      'Wednesday': [1, 1, 0, 0],
                      'Thursday': [0, 0, 0, 0]}},
  { 'RoomID': 14,
    'RoomName': 'مرسم 2',
    'Capacity': 20,
    'Type': 0,
    'Availability': { 'Saturday': [1, 1, 0, 0],
                      'Sunday': [0, 0, 0, 0],
                      'Monday': [1, 1, 0, 0],
                      'Tuesday': [0, 0, 0, 0],
                      'Wednesday': [0, 0, 0, 0],
                      'Thursday': [1, 1, 0, 0]}},
  { 'RoomID': 13,
    'RoomName': 'معمل 4',
    'Capacity': 25,
    'Type': 0,
    'Availability': { 'Saturday': [1, 1, 0, 0],
                      'Sunday': [1, 1, 1, 1],
                      'Monday': [0, 1, 1, 0],
                      'Tuesday': [1, 1, 1, 1], # <-- Note: Original had [1,1,1,1], using yours [0,1,1,1]
                      'Wednesday': [0, 0, 0, 0],
                      'Thursday': [0, 0, 0, 0]}},
  { 'RoomID': 15,
    'RoomName': 'مرسم 1',
    'Capacity': 15,
    'Type': 0,
    'Availability': { 'Saturday': [0, 0, 0, 0],
                      'Sunday': [1, 1, 1, 1],
                      'Monday': [0, 0, 1, 1],
                      'Tuesday': [0, 0, 1, 0],
                      'Wednesday': [1, 1, 0, 0],
                      'Thursday': [1, 1, 1, 1]}}]


# --- Data for: Transformed_Courses ---
Transformed_Courses = [
    { 'CourseID': 51,
    'CourseName': 'تنظيم حاسوب',
    'Type': 0,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 52,
    'CourseName': 'إدارة قواعد البيانات',
    'Type': 0,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 53,
    'CourseName': 'تطوير تطبيقات الويب',
    'Type': 0,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 54,
    'CourseName': 'نظم تشغيل',
    'Type': 0,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 55,
    'CourseName': 'هياكل البيانات والخوارزميات',
    'Type': 0,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 56,
    'CourseName': 'إدارة الأنظمة والشبكات',
    'Type': 0,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 57,
    'CourseName': 'برمجة تكاملية',
    'Type': 0,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 58,
    'CourseName': 'تجارة الكترونية',
    'Type': 0,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 59,
    'CourseName': 'تطوير تطبيقات الموبايل',
    'Type': 0,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 60,
    'CourseName': 'هندسة برمجيات',
    'Type': 0,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 61,
    'CourseName': 'تحقيق جنائي رقمي',
    'Type': 0,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 62,
    'CourseName': 'إدارة مشاريع تقنية المعلومات',
    'Type': 0,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 63,
    'CourseName': 'إنترنت الأشياء',
    'Type': 0,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 64,
    'CourseName': 'برمجة 2',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
    { 'CourseID': 87,
    'CourseName': 'ادارة مشاريع',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 65,
    'CourseName': 'جبر خطي',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 0,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 66,
    'CourseName': 'برمجة تكاملية',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 67,
    'CourseName': 'صراع عربي اسرائيلي',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 0,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 68,
    'CourseName': 'تطوير تطبيقات الموبايل',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 69,
    'CourseName': 'اساسيات تقنية',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 70,
    'CourseName': 'مناهج البحث العلمي',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 0,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 71,
    'CourseName': 'تحقيق جنائي رقمي',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 72,
    'CourseName': 'مبادئ المحاسبة',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 0,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 73,
    'CourseName': 'تجارة الكترونية',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 74,
    'CourseName': 'انجليزي',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 0,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 75,
    'CourseName': 'لغة عربية',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 0,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 76,
    'CourseName': 'إدارة مشاريع تقنية المعلومات',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 77,
    'CourseName': 'تنظيم حاسوب',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 78,
    'CourseName': 'إنترنت الأشياء',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 79,
    'CourseName': 'ادارة قواعد بيانات',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 80,
    'CourseName': 'تنقيب بيانات',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 81,
    'CourseName': 'إدارة الانظمة والشبكات',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 82,
    'CourseName': 'نظم تشغيل',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 83,
    'CourseName': 'هياكل البيانات والخوارزميات',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 84,
    'CourseName': 'تطوير تطبيقات الويب',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 85,
    'CourseName': 'برمجة 2',
    'Type': 0,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 86,
    'CourseName': 'هندسة برمجيات',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
    { 'CourseID': 88,
    'CourseName': 'تنقيب بيانات',
    'Type': 0,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 89,
    'CourseName': 'نظم دعم القرار',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 90,
    'CourseName': 'نظم استراتيجية',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},

  { 'CourseID': 96,
    'CourseName': 'فيزياء',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 0,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
    { 'CourseID': 91,
    'CourseName': 'تصميم معماري 1',
    'Type': 0,
    'LectureHours': 2,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 92,
    'CourseName': 'تاريخ العمارة',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 95,
    'CourseName': 'هندسة وصفية',
    'Type': 0,
    'LectureHours': 2,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 97,
    'CourseName': 'نظرية إنشاءات',
    'Type': 1,
    'LectureHours': 2,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 2,
    'TotalLectures': 12},
  { 'CourseID': 98,
    'CourseName': 'تصميم معماري 3',
    'Type': 0,
    'LectureHours': 4,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 2,
    'TotalLectures': 24},
  { 'CourseID': 99,
    'CourseName': 'تحكم بيئي',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 100,
    'CourseName': 'عمارة محلية',
    'Type': 1,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 101,
    'CourseName': 'تنسيق مواقع',
    'Type': 0,
    'LectureHours': 2,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 102,
    'CourseName': 'تصميم بالحاسوب 3d',
    'Type': 0,
    'LectureHours': 2,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 103,
    'CourseName': 'انشاء مباني ١',
    'Type': 0,
    'LectureHours': 2,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12},
  { 'CourseID': 104,
    'CourseName': 'نظرية عمارة 2',
    'Type': 0,
    'LectureHours': 1,
    'CourseTypeFlag': 1,
    'WeeklyLectures': 1,
    'TotalLectures': 12}]
# -- coding: utf-8 --
# Auto-generated data file - Filtered for IT Level 2 based on the provided schedule
# -- coding: utf-8 --
# --- Data for: doctor_local ---

# --- Standard Day/Time/Settings Data (from last prompt) ---

Days=[{'id': 1, 'day_name': 'Saturday'},{'id': 2, 'day_name': 'Sunday'},{'id': 3, 'day_name': 'Monday'},

     {'id': 4, 'day_name': 'Tuesday'},{'id': 5, 'day_name': 'Wednesday'},{'id': 6, 'day_name': 'Thursday'},{'id': 7, 'day_name': 'fri'}]



TimeSlots = [ {'id_slot': 1, 'slot_name': 1, 'start_timeslot': '08:00:00', 'end_timeslot': '10:00:00'},

              {'id_slot': 2, 'slot_name': 2, 'start_timeslot': '10:00:00', 'end_timeslot': '12:00:00'},

              {'id_slot': 3, 'slot_name': 3, 'start_timeslot': '12:00:00', 'end_timeslot': '14:00:00'},

              {'id_slot': 4, 'slot_name': 4, 'start_timeslot': '14:00:00', 'end_timeslot': '16:00:00'}]



GeneralSettings = [ { 'week_start_day_id': 1,'week_end_day_id': 6,'holiday_day_id': 7,

                      'max_lectures_per_day_department': 4,'min_lectures_per_day_department': 2,

                      'max_lectures_per_day_professor': 4,'min_lectures_per_day_professor': 2}]